/*******************************************************************************************************************
                             BOOKMARKET 연동 테이블                                  
--------------------------------------------------------------------------------------------------------------------

1. BOOKMARKET_MEMBER 테이블 생성
  - 컬럼 리스트 : 회원 아이디 - MID   /   VARCHAR2    /   PRIMARY KEY
                패스워드 - PASS    /   VARCHAR2    /   NOT NULL
                이름 - NAME   /   VARCHAR2
                주소 - ADDR    /   VARCHAR2    
                연락처 - PHONE    /   VARCHAR2
                가입일자 - MDATE   /   DATE
  
  
2. BOOKMARKET_BOOK 테이블 생성
  - 컬럼 리스트 : 도서아이디 BID   /   VARCHAR2(20)    /   PRIMARY KEY   ->    ISBN_0001(SEQUENCE 사용)
                도서명 - TITLE    /    VARCHAR2(100)    /   NOT NULL
                가격 - PRICE   /    NUMBER(8)
                저자 - AUTHOR    /   VARCHAR2(50)  
                설명 - INTRO    /   VARCHAR2(100)
                분야 - PART    /   VARCHAR2(30)
                출판일 - PDATE   /   VARCHAR2(50)
                이미지 파일명 - IMG    /   VARCHAR2(100)
                등록일 - BDATE    /  DATE
           
                        
3. BOOKMARKET_CART 테이블 생성
  - 컬럼 리스트 : 도서아이디 BID   /   VARCHAR2(20)    
                도서명 - TITLE    /    VARCHAR2(100)   
                가격 - PRICE   /    NUMBER(8)
                저자 - AUTHOR    /   VARCHAR2(50)  
                설명 - INTRO    /   VARCHAR2(100)


4. BOOKMARKET_ORDER 테이블 생성
  - 컬럼 리스트 : 도서아이디 BID   /   VARCHAR2(20)
                도서명 - TITLE    /    VARCHAR2(100)   
                가격 - PRICE   /    NUMBER(8)
                저자 - AUTHOR    /   VARCHAR2(50)  
                설명 - INTRO    /   VARCHAR2(100)

*******************************************************************************************************************/

-- CREATE
CREATE TABLE BOOKMARKET_MEMBER(
  MID   VARCHAR2(50)    CONSTRAINT    PK_BOOKMARKET_MEMBER_MID    PRIMARY KEY,
  PASS    VARCHAR2(50)    CONSTRAINT    NN_BOOKMARKET_MEMBER_PASS   NOT NULL,
  NAME    VARCHAR2(50),
  ADDR    VARCHAR2(100),
  PHONE   VARCHAR2(30),
  MDATE   DATE
);

-- ALTER
ALTER TABLE BOOKMARKET_MEMBER
ADD NAME VARCHAR2(50);
-- 확인
SELECT *FROM USER_TABLES WHERE TABLE_NAME = 'BOOKMARKET_MEMBER';
SELECT *FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'BOOKMARKET_MEMBER';
DESC BOOKMARKET_MEMBER;
SELECT *FROM BOOKMARKET_MEMBER;

-- INSERT INTO
SELECT *FROM BOOKMARKET_MEMBER;
INSERT INTO BOOKMARKET_MEMBER
VALUES ('HONG1234', '1234', '홍길동', '서울시 강남구 역삼동', '010-1234-5678', SYSDATE);
INSERT INTO BOOKMARKET_MEMBER
VALUES ('ADMIN1234', '1234', '관리자', '서울시 영등포구 여의도동', '010-1111-2222', SYSDATE-10);
INSERT INTO BOOKMARKET_MEMBER
VALUES ('TEST', '1234', '테스트', '서울시 영등포구 여의도동', '010-1999-0728', SYSDATE);


-- 저장
COMMIT;

-- GETLOGINRESULT -> 로그인 : SELECT ~ COUNT
SELECT MID, PASS FROM BOOKMARKET_MEMBER;
SELECT COUNT(*) FROM BOOKMARKET_MEMBER WHERE MID = ? AND PASS = ?;

-- SELECT

-- SEARCH

-- INSERT

-- DROP
DROP TABLE BOOKMARKET_BOOK;
DROP SEQUENCE SEQU_BOOKMARKET_BOOK_ISBN;

-- BOOKMARKET_BOOK
CREATE TABLE BOOKMARKET_BOOK(
  ISBN   VARCHAR2(20)    CONSTRAINT   PK_BOOKMARKET_BOOK_BID   PRIMARY KEY,
  TITLE   VARCHAR2(100)   CONSTRAINT    NN_BOOKMARKET_BOOK_TITLE    NOT NULL,
  PRICE   NUMBER(8),
  AUTHOR    VARCHAR2(50),
  INTRO   VARCHAR2(100),
  PART    VARCHAR2(30),
  PDATE   VARCHAR2(50),    -- 출판일
  IMG   VARCHAR2(100),      -- 이미지파일명
  BDATE   DATE                    -- 등록일
);
-- 확인
SELECT *FROM USER_TABLES WHERE TABLE_NAME = 'BOOKMARKET_BOOK';
SELECT *FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'BOOKMARKET_BOOK';
SELECT *FROM USER_SEQUENCES;
DESC BOOKMARKET_BOOK;
SELECT *FROM BOOKMARKET_BOOK;
-- SEQUENCE
CREATE SEQUENCE SEQU_BOOKMARKET_BOOK_ISBN
START WITH 1
INCREMENT BY 1;

-- INSERT
INSERT INTO BOOKMARKET_BOOK
VALUES ('ISBN_'||LTRIM(TO_CHAR(SEQU_BOOKMARKET_BOOK_ISBN.NEXTVAL, '0000')), 
'오라클', 27000, '고광일', '데이터 베이스 프로그래밍', 'IT', '2023/04/05', NULL, SYSDATE);
INSERT INTO BOOKMARKET_BOOK
VALUES ('ISBN_'||LTRIM(TO_CHAR(SEQU_BOOKMARKET_BOOK_ISBN.NEXTVAL, '0000')), 
'자바', 30000, '김자바', '자바 프로그래밍', 'IT', '2019/11/24', NULL, SYSDATE-10);
INSERT INTO BOOKMARKET_BOOK
VALUES ('ISBN_'||LTRIM(TO_CHAR(SEQU_BOOKMARKET_BOOK_ISBN.NEXTVAL, '0000')), 
'C언어', 12000, '최씨', 'C언어 프로그래밍', 'IT', '2007/01/19', NULL, SYSDATE-150);
INSERT INTO BOOKMARKET_BOOK
VALUES ('ISBN_'||LTRIM(TO_CHAR(SEQU_BOOKMARKET_BOOK_ISBN.NEXTVAL, '0000')), 
'해리포터', 21000, 'JK롤링', '해리포터와 마법학교', '판타지 소설', '2010/03/04', NULL, SYSDATE-600);
INSERT INTO BOOKMARKET_BOOK
VALUES ('ISBN_'||LTRIM(TO_CHAR(SEQU_BOOKMARKET_BOOK_ISBN.NEXTVAL, '0000')), 
'신데렐라', 7000, '박신데', '신데렐라와 유리구두', '동화책', '1980/06/30', NULL, SYSDATE-1500);
INSERT INTO BOOKMARKET_BOOK
VALUES ('ISBN_'||LTRIM(TO_CHAR(SEQU_BOOKMARKET_BOOK_ISBN.NEXTVAL, '0000')), 
'콩쥐팥쥐', 5500, '이콩쥐', '잔치하나로 인생핀 콩쥐', '동화책', '1967/09/16', NULL, SYSDATE-1630);

-- SELECT
SELECT *FROM BOOKMARKET_BOOK ORDER BY ISBN ASC;

-- 저장
COMMIT;




-- 파일명 업데이트
UPDATE BOOKMARKET_BOOK SET IMG='ISBN1235.jpg'
WHERE ISBN='ISBN_0004';
UPDATE BOOKMARKET_BOOK SET IMG='ISBN1236.jpg'
WHERE ISBN='ISBN_0005';
COMMIT;
SELECT * FROM BOOKMARKET_BOOK;

--"도서ID", "도서명", "단가", "수량", "총가격" : 어떤 회원이 어떤도서를 몇권 장바구니에 추가했는지
--  BOOKMARKET_CART : 장바구니(CID, CDATE, QTY, ISBN, MID) 
SELECT * FROM BOOKMARKET_MEMBER;
SELECT * FROM BOOKMARKET_BOOK;
CREATE TABLE BOOKMARKET_CART(
    CID    VARCHAR2(30)   CONSTRAINT PK_BOOKMARKET_CART_CID  PRIMARY KEY,
    CDATE   DATE,
    QTY     NUMBER(4),
    ISBN   VARCHAR2(20),
    MID   VARCHAR2(50),
      CONSTRAINT FK_BOOKMARKET_CART_ISBN   FOREIGN KEY  (ISBN)
                                     REFERENCES  BOOKMARKET_BOOK(ISBN),
      CONSTRAINT FK_BOOKMARKET_CART_MID  FOREIGN KEY (MID)
                                     REFERENCES  BOOKMARKET_MEMBER(MID)
);
SELECT * FROM USER_TABLES WHERE  TABLE_NAME LIKE 'BOOKMARKET%';
DESC BOOKMARKET_CART;
-- CID에 사용할  시퀀스 생성
CREATE SEQUENCE SEQU_BOOKMARKET_CART_CID
   START WITH 1
   INCREMENT BY 1;
SELECT * FROM USER_SEQUENCES;   
SELECT * FROM BOOKMARKET_CART;
DESC BOOKMARKET_BOOK;

SELECT 'C_'||LTRIM(TO_CHAR(SEQU_BOOKMARKET_CART_CID.NEXTVAL,'0000'))
FROM DUAL;
SELECT *FROM BOOKMARKET_CART;

DROP TABLE BOOKMARKET_CART;
DROP SEQUENCE SEQU_BOOKMARKET_CART_CID;

-- ISBN이 


-- INSERTCHECK
SELECT COUNT(*) FROM BOOKMARKET_CART WHERE MID = ? AND ISBN = ?;

-- UPDATEQTY
UPDATE BOOKMARKET_CART SET QTY = QTY + 1 WHERE CID = 'C_0003';
UPDATE BOOKMARKET_CART SET QTY = QTY + 1 WHERE MID = 'HONG1234' AND ISBN = 'ISBN_0001';

-- SELECT : Object[] tableHeader = { "번호", "도서ID", "도서명", "단가", "수량", "총가격" };
SELECT ROWNUM, ISBN, TITLE, PRICE, TO_CHAR(PRICE, 'L999,999') SPRICE, 
              QTY, QTY*PRICE TOTAL_PRICE, TO_CHAR(QTY*PRICE, 'L999,999') STOTAL_PRICE, CID
FROM (SELECT B.ISBN, B.TITLE, B.PRICE, C.QTY, C.MID, C.CID
            FROM BOOKMARKET_CART C, BOOKMARKET_BOOK B, BOOKMARKET_MEMBER M
            WHERE C.MID = M.MID AND B.ISBN = C.ISBN)
WHERE MID = 'HONG1234';

SELECT ROWNUM, ISBN, TITLE, PRICE, TO_CHAR(PRICE, 'L999,999') SPRICE, QTY, 
QTY*PRICE TOTAL_PRICE, TO_CHAR(QTY*PRICE, 'L999,999') STOTAL_PRICE 
FROM (SELECT B.ISBN, B.TITLE, B.PRICE, C.QTY, C.MID 
FROM BOOKMARKET_CART C, BOOKMARKET_BOOK B, BOOKMARKET_MEMBER M 
WHERE C.MID = M.MID AND B.ISBN = C.ISBN) 
WHERE MID = '';

-- REMOVE
UPDATE BOOKMARKET_CART SET QTY = QTY - 1 WHERE MID = 'HONG1234' AND ISBN = 'ISBN_0001';
DELETE FROM BOOKMARKET_CART WHERE MID = ? AND ISBN = ? AND QTY = 0;
DELETE FROM BOOKMARKET_CART WHERE MID = 'HONG1234';

COMMIT;

-- ORDERUSER
-- SELECT
SELECT ROWNUM, MID, NAME, ADDR, PHONE, CDATE 
FROM (SELECT M.MID, M.NAME, M.ADDR, M.PHONE, C.CDATE
            FROM BOOKMARKET_CART C, BOOKMARKET_MEMBER M
            WHERE C.MID = M.MID)
WHERE MID = 'HONG1234' AND ROWNUM = 1;


-- BOOKMARKET_ORDER
CREATE TABLE BOOKMARKET_ORDER(
    OID    VARCHAR2(30)   CONSTRAINT NN_BOOKMARKET_ORDER_OID  NOT NULL,
    ODATE   VARCHAR2(50),
    QTY     NUMBER(4),
    ISBN   VARCHAR2(20),
    MID   VARCHAR2(50),
    NAME    VARCHAR2(50),
    PHONE   VARCHAR2(50),
    ADDR    VARCHAR2(50),
      CONSTRAINT FK_BOOKMARKET_ORDER_ISBN   FOREIGN KEY  (ISBN)
                                     REFERENCES  BOOKMARKET_BOOK(ISBN),
      CONSTRAINT FK_BOOKMARKET_ORDER_MID  FOREIGN KEY (MID)
                                     REFERENCES  BOOKMARKET_MEMBER(MID)
);

-- 
SELECT *FROM BOOKMARKET_ORDER;
SELECT *FROM USER_TABLES WHERE TABLE_NAME = 'BOOKMARKET_ORDER';
SELECT *FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'BOOKMARKET_ORDER';

-- BOOK INSERT
INSERT INTO BOOKMARKET_BOOK(ISBN, TITLE, PRICE, AUTHOR, INTRO, PART, PDATE, IMG, BDATE)
VALUES ('ISBN_'||LTRIM(TO_CHAR(SEQU_BOOKMARKET_BOOK_ISBN.NEXTVAL, '0000'), ?, ?, ?, ?, ?, ?, NULL, SYSDATE);

COMMIT;
